package main

// binder is the subset of webview2.WebView (Windows) and webview.WebView (macOS) that
// bindCommonBackend needs. Both concrete types already implement Bind(name string, f
// interface{}) error with this exact signature, so no adapter is required on either side.
type binder interface {
	Bind(name string, f interface{}) error
}

// bindCommonBackend wires every backend_X -> app.Y bind that is byte-identical (same JS name,
// same Go method value) on both Windows (window_windows.go) and macOS (window_darwin.go). It
// exists purely to avoid maintaining ~90 duplicate lines in two files; each platform file still
// binds its own platform-specific and inline-closure entries directly after calling this.
//
// Errors are discarded here exactly as they were at each call site before this extraction:
// webview2 and webview_go's Bind only fails for a duplicate name or an unsupported Go value, both
// of which are programming errors caught by platform_bridge_parity_test.go, not something to
// handle at runtime.
func bindCommonBackend(w binder, app *App) {
	_ = w.Bind("backend_getAppVersion", app.GetAppVersion)
	_ = w.Bind("backend_getAppInfo", app.GetAppInfo)
	_ = w.Bind("backend_getPlatformCapabilities", app.GetPlatformCapabilities)
	_ = w.Bind("backend_getConfig", app.GetConfig)
	_ = w.Bind("backend_saveConfig", app.SaveConfig)
	_ = w.Bind("backend_exportConfig", app.ExportConfig)
	_ = w.Bind("backend_importConfig", app.ImportConfig)
	_ = w.Bind("backend_packListExportable", app.PackListExportable)
	_ = w.Bind("backend_packExport", app.PackExport)
	_ = w.Bind("backend_packInspect", app.PackInspect)
	_ = w.Bind("backend_packImport", app.PackImport)
	_ = w.Bind("backend_runCommandFilter", app.RunCommandFilter)
	_ = w.Bind("backend_runCommandFilterAsync", app.RunCommandFilterAsync)
	_ = w.Bind("backend_generateCliCommandAsync", app.GenerateCliCommandAsync)
	_ = w.Bind("backend_validateCliCommand", app.ValidateCliCommand)
	_ = w.Bind("backend_cancelCommandFilter", app.CancelCommandFilter)
	_ = w.Bind("backend_getSession", app.GetSession)
	_ = w.Bind("backend_saveSession", app.SaveSession)
	_ = w.Bind("backend_getStartupFile", app.GetStartupFile)
	_ = w.Bind("backend_openFile", app.OpenFile)
	_ = w.Bind("backend_saveFile", app.SaveFile)
	_ = w.Bind("backend_saveFileChecked", app.SaveFileChecked)
	_ = w.Bind("backend_saveFileAs", app.SaveFileAs)
	_ = w.Bind("backend_exportPlainTextAs", app.ExportPlainTextAs)
	_ = w.Bind("backend_openFolder", app.OpenFolder)
	_ = w.Bind("backend_scanFolderFiles", app.ScanFolderFiles)
	_ = w.Bind("backend_readFileByPath", app.ReadFileByPath)
	_ = w.Bind("backend_queryLLMAsync", app.QueryLLMAsync)
	_ = w.Bind("backend_queryVisionAsync", app.QueryVisionAsync)
	_ = w.Bind("backend_generateImageAsync", app.GenerateImageAsync)
	_ = w.Bind("backend_autocompleteAsync", app.AutocompleteAsync)
	_ = w.Bind("backend_trimMemory", app.TrimMemory)
	_ = w.Bind("backend_uiReady", app.MarkUIReady)
	_ = w.Bind("backend_closeWindow", app.CloseWindow)
	_ = w.Bind("backend_updateGlobalShortcut", app.UpdateGlobalShortcut)
	_ = w.Bind("backend_searchScraps", app.SearchScraps)
	_ = w.Bind("backend_searchScrapsAsync", app.SearchScrapsAsync)
	_ = w.Bind("backend_searchScrapsSemanticAsync", app.SearchScrapsSemanticAsync)
	_ = w.Bind("backend_scrapFilterOptionsAsync", app.ScrapFilterOptionsAsync)
	_ = w.Bind("backend_tagEditAsync", app.TagEditAsync)
	_ = w.Bind("backend_deepSearchPlanAsync", app.DeepSearchPlanAsync)
	_ = w.Bind("backend_deepSearchRunAsync", app.DeepSearchRunAsync)
	_ = w.Bind("backend_cancelDeepSearch", app.CancelDeepSearch)
	_ = w.Bind("backend_lessonPlanAsync", app.LessonPlanAsync)
	_ = w.Bind("backend_lessonRunAsync", app.LessonRunAsync)
	_ = w.Bind("backend_cancelLesson", app.CancelLesson)
	_ = w.Bind("backend_lessonSaveAsync", app.LessonSaveAsync)
	_ = w.Bind("backend_lessonsInfoAsync", app.LessonsInfoAsync)
	_ = w.Bind("backend_semanticStatusAsync", app.SemanticStatusAsync)
	_ = w.Bind("backend_semanticUpdateAsync", app.SemanticUpdateAsync)
	_ = w.Bind("backend_cancelSemanticUpdate", app.CancelSemanticUpdate)
	_ = w.Bind("backend_printPreviewAsync", app.PrintPreviewAsync)
	_ = w.Bind("backend_printPickPdfPath", app.PrintPickPdfPath)
	_ = w.Bind("backend_printSavePdfAsync", app.PrintSavePdfAsync)
	_ = w.Bind("backend_printPreviewClose", app.PrintPreviewClose)
	_ = w.Bind("backend_triggerGitSync", app.TriggerGitSync)
	_ = w.Bind("backend_getGitRepoStatus", app.GetGitRepoStatus)
	_ = w.Bind("backend_setupGitRemote", app.SetupGitRemote)
	_ = w.Bind("backend_checkGitInstalled", app.CheckGitInstalled)
	_ = w.Bind("backend_testGitRemote", app.TestGitRemote)
	_ = w.Bind("backend_testDiscordBridgeConnection", app.TestDiscordBridgeConnection)
	_ = w.Bind("backend_reportRPCResult", app.ReportRPCResult)
	_ = w.Bind("backend_parseSlotsRPC", app.ParseSlotsRPC)
	_ = w.Bind("backend_runSlotAgentAsync", app.RunSlotAgentAsync)
	_ = w.Bind("backend_cancelSlotAgent", app.CancelSlotAgent)
	_ = w.Bind("backend_getSlotHoverPeek", app.GetSlotHoverPeek)
	_ = w.Bind("backend_watchActiveFile", app.WatchActiveFile)
	_ = w.Bind("backend_unwatchActiveFile", app.UnwatchActiveFile)
	_ = w.Bind("backend_getDefaultAgentsConfigYAML", app.GetDefaultAgentsConfigYAML)
	_ = w.Bind("backend_getDefaultAgentsConfigMarkdown", app.GetDefaultAgentsConfigMarkdown)
	_ = w.Bind("backend_getActiveAgentsConfigStatus", app.GetActiveAgentsConfigStatus)
	_ = w.Bind("backend_getActiveSlotConfigJSON", app.GetActiveSlotConfigJSON)
	_ = w.Bind("backend_checkAgentAvailability", app.CheckAgentAvailability)
	_ = w.Bind("backend_detectLLMProvider", app.DetectLLMProvider)
	_ = w.Bind("backend_updateActiveAgentsConfigDefaultAgent", app.UpdateActiveAgentsConfigDefaultAgent)
	_ = w.Bind("backend_exportAgentsConfigFile", app.ExportAgentsConfigFile)
	_ = w.Bind("backend_importAgentsConfigFile", app.ImportAgentsConfigFile)
	_ = w.Bind("backend_openAgentsConfigFile", app.OpenAgentsConfigFile)
	_ = w.Bind("backend_jevPredict", app.JevPredict)
	_ = w.Bind("backend_jevPredictAsync", app.JevPredictAsync)
	_ = w.Bind("backend_jevExecute", app.JevExecute)
	_ = w.Bind("backend_jevExecuteAsync", app.JevExecuteAsync)
	_ = w.Bind("backend_jevVerify", app.JevVerify)
	_ = w.Bind("backend_jevDispatchAgent", app.JevDispatchAgent)
	_ = w.Bind("backend_jevPruneContext", app.JevPruneContext)
	_ = w.Bind("backend_startMobileDrop", app.StartMobileDrop)
	_ = w.Bind("backend_startMobileDropWithVoice", app.StartMobileDropWithVoice)
	_ = w.Bind("backend_setMobileDropSharedText", app.SetMobileDropSharedText)
	_ = w.Bind("backend_cancelMobileDrop", app.CancelMobileDrop)
	_ = w.Bind("backend_requestMobileDropTunnelAsync", app.RequestMobileDropTunnelAsync)
	_ = w.Bind("backend_saveAsset", app.SaveAsset)
	_ = w.Bind("backend_importAssetFile", app.ImportAssetFile)
	_ = w.Bind("backend_openPath", app.OpenPath)
	_ = w.Bind("backend_revealPath", app.RevealPath)
	_ = w.Bind("backend_transcribeAudioAsync", app.TranscribeAudioAsync)
	_ = w.Bind("backend_meetingRecordingSupported", app.MeetingRecordingSupported)
	_ = w.Bind("backend_checkMeetingAudioAsync", app.CheckMeetingAudioAsync)
	_ = w.Bind("backend_retypeWithImeAsync", app.RetypeWithImeAsync)
	_ = w.Bind("backend_startMeetingRecording", app.StartMeetingRecording)
	_ = w.Bind("backend_stopMeetingRecordingAsync", app.StopMeetingRecordingAsync)
	_ = w.Bind("backend_abortMeetingRecording", app.AbortMeetingRecording)
	_ = w.Bind("backend_getSpeechStatus", app.GetSpeechStatus)
	_ = w.Bind("backend_installSpeechPartAsync", app.InstallSpeechPartAsync)
	_ = w.Bind("backend_cancelSpeechInstall", app.CancelSpeechInstall)
	_ = w.Bind("backend_removeSpeechPart", app.RemoveSpeechPart)
	_ = w.Bind("backend_validateWhisperModelFile", app.ValidateWhisperModelFile)
	_ = w.Bind("backend_pickFilePath", app.PickFilePath)
	_ = w.Bind("backend_openInboxFolder", app.OpenInboxFolder)
	_ = w.Bind("backend_retryVoiceCacheAsync", app.RetryVoiceCacheAsync)
	_ = w.Bind("backend_keepVoiceCache", app.KeepVoiceCache)
	_ = w.Bind("backend_discardVoiceCache", app.DiscardVoiceCache)
	_ = w.Bind("backend_openExternal", app.OpenExternal)
	_ = w.Bind("backend_checkOllamaRunning", app.CheckOllamaRunning)
	_ = w.Bind("backend_startOllamaService", app.StartOllamaService)
	_ = w.Bind("backend_stopOllamaService", app.StopOllamaService)
	_ = w.Bind("backend_setupOllamaGemma4Async", app.SetupOllamaGemma4Async)
	_ = w.Bind("backend_cancelOllamaSetup", app.CancelOllamaSetup)
}
