// Writes img/manual/shots.md (the brief for the documentation writers) from shots.json and the
// pictures that exist on disk. Rewritten after every run, so it always matches the files.
import fs from 'node:fs';
import path from 'node:path';

function pngSize(file) {
  const b = fs.readFileSync(file);
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20), kb: b.length / 1024 };
}

export function writeShotsMd({ shots, imgRoot, results }) {
  const stale = new Map();
  for (const r of results || []) {
    if (r.stale) stale.set(r.shot, r.stale);
  }
  const lines = [];
  lines.push('# Manual screenshots');
  lines.push('');
  lines.push('Generated by `tools/docshots/run.mjs` (see `tools/docshots/README.md`). Every picture exists twice with the same file name:');
  lines.push('`img/manual/ja/<name>.png` (Japanese UI) and `img/manual/en/<name>.png` (English UI). Demo data only; nothing private.');
  lines.push('');
  lines.push('Full pictures are the application client area at 1120x720 px (no window frame); the two phone pictures are the phone page at 390x844 px.');
  lines.push('Crops are cut from a full picture and are marked "crop". Numbered call-outs are filled circles (#e8743b, white ring, white bold digit)');
  lines.push('baked into the image; the digits are the same in both languages and are explained per picture below. The pictures contain no other');
  lines.push('annotation text. Everything shown is demo data on a fixed date (2026-09-18).');
  lines.push('');
  for (const shot of shots.shots) {
    const files = ['ja', 'en'].map((l) => ({ l, file: path.join(imgRoot, l, shot.name + '.png') }));
    const present = files.filter((f) => fs.existsSync(f.file)).map((f) => ({ ...f, ...pngSize(f.file) }));
    lines.push(`## ${shot.name}`);
    lines.push('');
    lines.push(`- Files: \`img/manual/ja/${shot.name}.png\`, \`img/manual/en/${shot.name}.png\``);
    if (present.length) {
      const dims = [...new Set(present.map((p) => `${p.w}x${p.h}`))];
      lines.push(`- Size: ${dims.join(' / ')} px (${present.map((p) => `${p.l} ${p.kb.toFixed(0)} KB`).join(', ')})`);
    } else {
      lines.push('- Size: not produced yet');
    }
    lines.push(`- Kind: ${shot.size === 'crop' ? 'crop of a full picture' : 'full picture'}`);
    lines.push(`- State: ${shot.description}`);
    if (shot.notes) lines.push(`- Note: ${shot.notes}`);
    if (stale.has(shot.name)) lines.push(`- **Needs re-run**: ${stale.get(shot.name)}`);
    if (shot.markers && shot.markers.length) {
      lines.push('- Markers:');
      for (const m of shot.markers) lines.push(`  ${m.n}. ${m.meaning}`);
    } else {
      lines.push('- Markers: none');
    }
    lines.push('');
  }
  fs.writeFileSync(path.join(imgRoot, 'shots.md'), lines.join('\n'), 'utf8');
}
